### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by rotan1** [agamemnus/cordova-plugin-ondestroy#1]
Hi, 

After rename window.plugins.OnDestroy. to window.plugins.OnDestroyPlugin and add a log error in the exec function in javascript I get a Class Not Found error.

I checked all configs files but I din't notice wrong compare to other Cordova's Plugin.

Have you an idea ?

Thanks

**Comment by agamemnus** [comment]
I don't know.

Make sure you are modifying the code in the /plugins directory, then re-install the plugin from there.

... wait, I am actually not sure what you are saying. I think my example is wrong. It should be window.plugins.OnDestroyPlugin not OnDestroy. What else did you change?

**Comment by agamemnus** [comment]
Another question... what Cordova version are you using?

**Comment by rotan1** [comment]
I just modified the 'undefined' in cordova.exec function in the javascript file and replaced it by a simple console log which tells me the Class Not Found Error.

I tried to edit the java class without success.
I'm using the last version 5.1.1 of Cordova.

**Comment by agamemnus** [comment]
Only the callback is used. I'm still not clear on what you did. Maybe you can fork my project and show me?

**Comment by rotan1** [comment]
Ok, I did it.

**Comment by agamemnus** [comment]
In config.xml, modify <clobbers>. I don't know how you would have even had
an error without changing that... Change the the clobbers target property
to window.plugins.OnDestroy. If that doesn't work search for other
instances of "OnDestroyPlugin". (Java filename too!)

Change only in plugin directory then reinstall from it.. or your fork.

**Comment by rotan1** [comment]
I tried many things but I can't fix it. I replaced all OnDestroyPlugin to OnDestroy on my fork but it keep saying class not found... I don't know well Cordova plugins so I'm little lost.

**Comment by agamemnus** [comment]
Ok, give me some time and I'll test it myself.

**Comment by agamemnus** [comment]
@rotan1, I just tried some different code. Try `cordova plugin add https://github.com/agamemnus/cordova-plugin-ondestroy#ondestroy`. If that doesn't work, maybe you can make and link a sample test project to help me debug?

**Comment by rotan1** [comment]
I created a Cordova Android test app using Eclipse and your plugin.

I forked your repository to integrate a console.log in the error function of your plugin's JavaScript file.

When I launch my Android test app, it pops up the "Class not found" error.

I created a repository with this test app for you to test: https://github.com/rotan1/cordova-test-android-app

Thanks

**Comment by agamemnus** [comment]
I only use command line.

There is no platforms/android or config.xml in your project so I can't test
it properly.

**Comment by rotan1** [comment]
You still can do it from the command line. There's a config.xml file in the www folder.

You can execute classic cordova commands to create a new project and then paste our code inside it, using the plugin and so on.

**Comment by jelarpong** [comment]
# try this

### go to plugin folder => com.flyingsoftgames.ondestroyplugin 

### in ondestroyplugin.js
//======================================================
```
var onDestroy = {
    onset: function(successCallback, errorCallback) {
        errorCallback = errorCallback || this.errorCallback;
        cordova.exec(successCallback, errorCallback, 'OnDestroyPlugin', 'setEventListener', []);
    },

    errorCallback: function() {
        console.log("WARNING: OnDestroy errorCallback not implemented");
    }
};

module.exports = onDestroy;
```
//======================================================

### in plugin.xml
//======================================================
```edit clobbers target to => "window.onDestroy"```
//======================================================

```
onDestroy.onset(sucfn,errfn);
```

**Comment by agamemnus** [comment]
Sorry for not getting back to you... did you manage to get it working?
