### ISSUE TITLE
Can't make it worked

### ISSUE THREAD

**Issue by aorfevre** [agamemnus/cordova-plugin-ondestroy#2]
Hi,

I tried too to make your plugin work, without success yet.

Well, I've seen that your main branch it was mapped on OnDestroyPlugin.
I tried therefore the following 
window.plugins.OnDestroyPlugin.setEventListener(function(){ alert('test')})

I tried also your #ondestroy branch , with changing the name of the plugin 
window.plugins.OnDestroy.setEventListener(function(){ alert('test')})

My use case is the following : 
- user clicks home button (app is in background)
- user long press android home and see running process
- user swipe my app => I was expecting my alert  (I tried also with a console.log)

Any suggestions ?
What am I doing wrong ?

**Comment by agamemnus** [comment]
I don't know about alerts. Probably something to do with the way alerts work in particular. To test if the function runs, have your code set a flag in a database on your server via AJAX or something.
