### ISSUE TITLE
missing plugin in www.npmjs.com

### ISSUE THREAD

**Issue by mshahidjanjua** [agamemnus/cordova-plugin-ondestroy#5]
kindly add this plugin in www.npmjs.com. So we may use it in the build.phonegap.com apps.

Thanks

**Comment by agamemnus** [comment]
Ok. Will do.

**Comment by mshahidjanjua** [comment]
Thanks agamemnus. I am looking forward for your update. 
Then I'll process my app for client demo.

**Comment by agamemnus** [comment]
I need some help on this.

I don't know how to actually add the package to npm. I created an account on the website but I don't know how to log in with the command line.

This only seems to show how to create an account, and not log in:
https://gist.github.com/coolaj86/1318304

**Comment by mshahidjanjua** [comment]
Sure.

Here are the steps you may follow to publish your plugin on npmjs.com
Note: if it asks you to login in npmjs then use your account id and password of npmjs.com 
1. cordova plugin add github_url (in your phonegap project)
2. From the main project folder in command prompt (CLI)
-> cd plugins
-> cd plugin id
3. in plugin folder
plugman createpackagejson %cd%
4. npm publish

**Comment by agamemnus** [comment]
Having some trouble with plugman. Doesn't seem to work.

I tried:
`plugman create --name ondestroyplugin --plugin_id com.flyingsoftgames.ondestroyplugin --plugin_version 1`

Then, I did "npm publish", but I got an error:

`Could not install .`

`npm ERR! Error: ENOENT, open 'C:\mr_jigtato_free\plugins\com.flyingsoftgames.ond
estroyplugin\package.json'`

**Comment by mshahidjanjua** [comment]
You may simply use this command to get your plugin install in  phonegap project.
cordova plugin add https://github.com/agamemnus/cordova-plugin-ondestroy

---

**Comment by mshahidjanjua** [comment]
I give you a video which is really helpful as well.

https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-configuring-npm-and-creating-a-package-json

**Comment by agamemnus** [comment]
I already added the plugin into my project. The problem is adding it to npm. Would rather not listen/watch a video.

**Comment by mshahidjanjua** [comment]
Great. then you don't need this command.
plugman create --name ondestroyplugin --plugin_id com.flyingsoftgames.ondestroyplugin --plugin_version 1

**Comment by mshahidjanjua** [comment]
you can login in command prompt using 
npm adduser
command

**Comment by agamemnus** [comment]
Um, ok, so "adduser" is actually just a login. So then I need to add a package.json? What would that actually be?

**Comment by mshahidjanjua** [comment]
then you must have a package.json. Like this
http://screencast.com/t/22fOg7nR8D

**Comment by agamemnus** [comment]
Ok, this is going to take a bit. I will let you know.

**Comment by mshahidjanjua** [comment]
Sure

**Comment by agamemnus** [comment]
It is published as "CordovaOnDestroyPlugin". Can you look through it (especially the package.json) and make sure everything is correct? (conventions, etc.) Not sure if "CordovaOnDestroyPlugin" is the right naming for it.. let me know.

**Comment by mshahidjanjua** [comment]
I think cordova-plugin-ondestroy name was more professional and simple. it will look great if you able to update it. Then its name and id will be same.

**Comment by agamemnus** [comment]
How would I update it? :/

**Comment by mshahidjanjua** [comment]
simply update the name and higher version in the package.json and publish it as you did last time.

**Comment by agamemnus** [comment]
Ok, I did it, but without changing the version.

**Comment by mshahidjanjua** [comment]
It added a new package.
https://www.npmjs.com/~agamemnus

**Comment by mshahidjanjua** [comment]
You may delete the last one.

**Comment by agamemnus** [comment]
Lol, how? Sorry.

**Comment by mshahidjanjua** [comment]
https://docs.npmjs.com/cli/unpublish

**Comment by agamemnus** [comment]
Great. Thanks!

**Comment by mshahidjanjua** [comment]
You are welcome. Let me install and test this plugin in app.

**Comment by mshahidjanjua** [comment]
Hi

your plugn on github and npmjs.com has plugin id cordova-plugin-ondestroy but in plugin.xml on github  

it has different id.
http://screencast.com/t/XUocmoc3

This caused the plugin error in accessing it from npm.js.

Kindly update the plugin id on github.

Then kindly update this plugin on npmjs.com

So all these ids sync with each other and work accordingly.

I am looking forward for your response.

**Comment by agamemnus** [comment]
Well, as far as I could tell, the convention for the "id" in plugin.xml is to use dots ("."), while dashes are customary for a github name.

Same for the "param" tag and the "source-file" tag... I did what seemed to be customary.

I am not sure what the best way to do it is because it seems I would have conflicts in any scenario.

Maybe you can fork it and suggest the best way?

**Comment by mshahidjanjua** [comment]
As far npmjs.com concerned, "-" is recommended for package name and plugin id. We may use "." as well. But in both cases package name and plugin id must be same. Because this conflict cause an error.

http://screencast.com/t/9KHjAA3caEpv

Here is an example by cordova apache plugin cordova-plugin-file with same package name and id on github.com and on npmjs.com. 
https://github.com/apache/cordova-plugin-file/blob/master/plugin.xml 

I think it would help you to clear my point.

**Comment by agamemnus** [comment]
What about these two? Any thoughts?

`<param name="android-package" value="com.flyingsoftgames.ondestroyplugin.OnDestroyPlugin"/>`

`<source-file src="src/android/OnDestroyPlugin.java" target-dir="src/com/flyingsoftgames/ondestroyplugin" />`

**Comment by mshahidjanjua** [comment]
These can be different and have no impact on the plugin functionality. So no need to change them

like 
https://github.com/katzer/cordova-plugin-background-mode/blob/master/plugin.xml

plugin

has id and github package name are same 

http://screencast.com/t/3TuI030b1LAk

But Android section may have different android-package and source-file values.

http://screencast.com/t/87CR5LTrhPW

I hope this point will also be clear for you.

Now you need to add a new version in github with the id change in plugin.xml.

and then publish that change update in npmjs.com.

hopefully it will resolve the issue.

**Comment by agamemnus** [comment]
Ok. I doubt anyone used it yet and I don't want to change the version, so I just updated it... let me know...

**Comment by mshahidjanjua** [comment]
The installed plugin will function properly on any app as it is not sync with github or npmjs. Only new installations  will have this change available. 

For update

package.json has old and different id.
http://screencast.com/t/fqnADLyVxIi

and also plugin.xml has old different id

http://screencast.com/t/7UJu58mhAzqj

Which section did you update?

**Comment by agamemnus** [comment]
I updated both files. This is strange. I will delete it and re-publish. (edit: deleted and republished...)

**Comment by mshahidjanjua** [comment]
I have sent a pull request name

[Plugin id Conflict on github and npmjs #7](https://github.com/agamemnus/cordova-plugin-ondestroy/pull/7)
to resolve this issue.

**Comment by agamemnus** [comment]
I didn't know name and id should be the same...

Can it keep the same version and still have it work?

**Comment by mshahidjanjua** [comment]
For plugin id and package-name same official cordova guidelines.
http://screencast.com/t/4YGDfYTEDCV

https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html
Also guidelines for guiding users about old and new id of the plugin.
http://screencast.com/t/P7eKj0dwHoTE

These guidelines will help users to work with both new and old plugin id.

With same version it will work installation from github.com.

To work with buid.phonegap.com apps, it needs to get update on npmjs.com with new version.

**Comment by agamemnus** [comment]
Because phonegap caches it or something? Ok, I'll just make it 1 though..

Try it now.

**Comment by mshahidjanjua** [comment]
Okay Thanks. Hopefully, I'll find a new version on npmjs.com with these changes.

**Comment by agamemnus** [comment]
https://www.npmjs.com/~agamemnus

Should be there.

**Comment by mshahidjanjua** [comment]
Thanks, I found the plugin change. Everything was looking nice but on calling plugin. It was creating undefined error. I debugged it and found that wrong clobber was used to call this plugin. I corrected it and it starting working fine. I updated README.md file and send a pull request as well. 

It will help everyone to correct use of this plugin.

This correct README.md also needs a version update on github and npmjs.com as well.

Thanks for coordinating and helping me to get this plugin work on build.phonegap.com

**Comment by agamemnus** [comment]
Maybe onDestroyPlugin is better here, to try to avoid conflicts? Just
wondering ..

**Comment by mshahidjanjua** [comment]
I also tried installing plugin directly from github. Also has the same issue. By updating onDestroyPlugin it also worked from github. 

Clobbers are used to access the plugin.
So it is
window.plugins.OnDestroy

So it should work according to the definition of the plugin.

**Comment by agamemnus** [comment]
I mean, why not just change:

`<clobbers target="window.plugins.OnDestroy" />`
to:
`<clobbers target="window.plugins.OnDestroyPlugin" />`

?

A lot of other things have "OnDestroyPlugin". I somehow inadvertently changed it on April 28...

**Comment by mshahidjanjua** [comment]
Oh, I see. I was also wondering that this was working few days back and now it is not. As you have updated again plugin.xml so kindly increase the version number on github and post this change to npmjs.com. So all things get sync.

I'll also need to update the apps on build.phonegap.com as clobber has changed its value.

I am looking forward for your update on this.

**Comment by agamemnus** [comment]
Ok, I made the changes.... hopefully that works.

**Comment by mshahidjanjua** [comment]
Thanks. It is working.

**Comment by agamemnus** [comment]
Excellent...!
