### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by abdurrahmanekr** [agamemnus/cordova-plugin-ondestroy#9]
Here is the steps that I applied
1-> I installed plugin that I mentioned above
2-> Here is the code inside app.js
```javascript
.
.
.
$ionicPlatform.ready(function() {
	window.plugins.OnDestroyPlugin.setEventListener (function() {
		localStorage.setItem("OnDestroyPlugin", true);
	});
});
.
.
.
````
3-> application is terminated
4-> application opened
5->  localStorage has not been added

**Comment by agamemnus** [comment]
Idk. Might want to ask someone in an ionic chat room. This is a really
simple plugin so they might know what's going on.

**Comment by greybax** [comment]
Have same issue.. When user swiped app for closing it off this event doesn't fired. But If user click x button for closing the app it event fired successfully.

**Comment by agamemnus** [comment]
The code overrides the onDestroy event. Maybe it just doesn't get called. Maybe another one does, or maybe it is a Cordova/Android bug.

**Comment by greybax** [comment]
I think mostly guys which are using to this plugin expects from it that they can do some stuff when application will be closed (via swipe or something else). But seems that this plugin not works as it expected. 

See http://stackoverflow.com/a/18361887/2173016 for more details

![activity_lifecycle](https://developer.android.com/images/activity_lifecycle.png)

**Comment by agamemnus** [comment]
Thanks.

Maybe I should add onPause in this plugin?

**Comment by greybax** [comment]
Could you please try this also http://stackoverflow.com/a/26882533/2173016

**Comment by agamemnus** [comment]
That graphic is great. I'll add it to the readme later on. So finalize() maybe? Or is it just best to use onPause instead? Thoughts?

https://developer.android.com/reference/java/lang/Object.html#finalize%28%29

**Comment by greybax** [comment]
Let's try to use `onPause` because, `finalize` can be a too late for using on some cases

**Comment by agamemnus** [comment]
Okay. I will just add that to this plugin. Maybe I should make a different plugin too. I don't know. Decisions..

**Comment by agamemnus** [comment]
Okay. I made the modifications here. No idea if it works, but it should, maybe. Can you try it out? (It is a little crude but I didn't want to change the original code...)

**Comment by greybax** [comment]
ok, will try now and let you know..)

**Comment by greybax** [comment]
seems that you should have

    private CallbackContext onPauseCallback = null;

instead of

    private CallbackContext onDestroyCallback = null;

here https://github.com/agamemnus/cordova-plugin-ondestroy/blob/master/src/android/OnPausePlugin.java#L14

**Comment by agamemnus** [comment]
Thanks. Good catch. Does it work with that fix?

**Comment by greybax** [comment]
here looks the same issue: https://github.com/agamemnus/cordova-plugin-ondestroy/blob/master/src/android/OnPausePlugin.java#L12

**Comment by agamemnus** [comment]
Oops. I can't help myself.

**Comment by greybax** [comment]
I'm not sure that it works. Seems that you you didn't initialize OnPausePlugin  in [plugin.xml](https://github.com/agamemnus/cordova-plugin-ondestroy/blob/master/plugin.xml) Please check it. My app just doesn't start if I'm using

```
window.plugins.OnPausePlugin.setOnPauseEventListener(() => {
...
});
```

**Comment by agamemnus** [comment]
Okay I made the change. Sorry. I haven't done Java coding like this in a few months.

**Comment by greybax** [comment]
after plugin installation and cordova build android I've got follow errors:

```
C:\myProj\platforms\android\src\com\flyingsoftgames\ondestroyplugin\OnPausePlugin.java:22: error: method does not override or implement a method from a supertype
 @Override public void onPause () {
 ^
C:\myProj\platforms\android\src\com\flyingsoftgames\ondestroyplugin\OnPausePlugin.java:24: error: method onPause in class CordovaPlugin cannot be applied to given types;
  super.onPause ();
       ^
  required: boolean
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
:compileDebugJavaWithJavac FAILED
Note: Recompile with -Xlint:deprecation for details.
2 errors
```

**Comment by agamemnus** [comment]
Okay one more. I changed it to `protected void`...

**Comment by agamemnus** [comment]
There is more here I think. Give me a minute.

**Comment by greybax** [comment]
```
C:\myProj\platforms\android\src\com\flyingsoftgames\ondestroyplugin\OnPausePlugin.java:24: error: method onPause in class CordovaPlugin cannot be applied to given types;
  super.onPause ();
       ^
  required: boolean
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

**Comment by agamemnus** [comment]
We might not need all this.

Just do:
` document.addEventListener("pause", yourPauseFunction, false);`

**Comment by agamemnus** [comment]
I just modified the code. But yeah, you might not need this plugin to use onPause.

**Comment by agamemnus** [comment]
Might not*.

**Comment by greybax** [comment]
Seems that now plugin has a successful build.
But main issue is still there. We couldn't catch event that app was closed

**Comment by agamemnus** [comment]
Ugh. Sorry. I keep forgetting things. You also need `document.addEventListener("deviceready", onDeviceReady, false)`: https://cordova.apache.org/docs/en/latest/cordova/events/events.html.

**Comment by greybax** [comment]
yes, I have this eventListener

**Comment by agamemnus** [comment]
Well, try without my plugin. Just according to the code there. Does it not run?

**Comment by greybax** [comment]
I've just reinstall my app on the phone and seems that plugin works!
`onPause` event is fired when we close app via swipe. Please bump the new version of plugin

**Comment by agamemnus** [comment]
(I did bump the version.)

Also: great. But if you don't use onDestroy, no need for my plugin.

**Comment by greybax** [comment]
please do it in npm also https://www.npmjs.com/package/cordova-plugin-ondestroy

**Comment by agamemnus** [comment]
IDK. Maybe I should just get rid of the JS code and leave it as a readme change only. It's kind of dumb.

**Comment by greybax** [comment]
ok, up to you

**Comment by greybax** [comment]
but seems that it doesn't works if I just use `document.addEventListener("pause", callback, false)` so we need to leave native code in this plugin for `onPause`

As you wrote in readme 

> window.plugins.OnDestroyPlugin.addOnPauseEventListener (function) // Same as "document.addEventListener("pause", function, false)".

it's not like that, because when we make swipe for close the app we need to override native `onPause` method

**Comment by agamemnus** [comment]
I removed that code since it wasn't needed. It's just Javascript!

**Comment by agamemnus** [comment]
So you tried:
```
document.addEventListener("deviceready", function () {
 document.addEventListener("pause", function () {
  // Do stuff..
})
})

```

?
